### ISSUE TITLE
Property 'entries' does not exist on type 'ObjectConstructor'.  TS2339

### ISSUE THREAD

**Issue by muescha** [byte-fe/react-model#130]
I have a:

2. [x] Issue:

    * [x] **Provide error messages including stacktrace** ❌

    * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/moyxon99jx)** 🚀
    * [x] Did you check this issue wasn't filed before? 🤔

    * [ ] Elaborate on your issue. What behavior did you expect? ❓

    * [x] State the versions of react-model and relevant libraries. Which browser / node / ... version? 🚧

```
TypeScript error in /Users/muescha/Work/react/xxx/node_modules/react-model/src/helper.ts(46,10):
Property 'entries' does not exist on type 'ObjectConstructor'.  TS2339

    44 | ) => {
    45 |   const ret: any = {}
  > 46 |   Object.entries<Action>(actions).forEach(([key, action]) => {
       |          ^
    47 |     ret[key] = consumerAction(action, modelContext)
    48 |   })
    49 |   return ret
```

      | Software         | Version(s) |
      | ---------------- | ---------- |
      | react-model           | 3.0.1 |
      | Node             | v10.15.3 |
      | react         | 16.9.0 |
      | Operating System | 10.14.5 (18F132) macOS MOjave |

```
├── @types/react@16.9.2 invalid
├── @types/react-dom@16.9.0 invalid
├── d3@5.12.0
├── d3blackbox@1.2.0
├── moment@2.24.0
├── moment-range@4.0.2
├── react@16.9.0
├── react-dates@21.1.0
├── react-dom@16.9.0
├── react-model@3.0.1
├── react-scripts@3.1.2
├── react-with-direction@1.3.1
└── typescript@3.6.3
```

**Comment by ArrayZoneYour** [comment]
Thanks for feedback💗. Can you provide a minimal sample project with tsconfig.json？I cannot reproduce this error 😢

**Comment by ArrayZoneYour** [comment]
@muescha 
https://stackoverflow.com/questions/45422573/property-entries-does-not-exist-on-type-objectconstructor

**Comment by muescha** [comment]
thx this resolves the problem.

PS: i was exporting an React project from codesandbox without changes ...
