### ISSUE TITLE
页面跳转时会存在一定几率的报错，特别是面包屑导航一层层回退时

### ISSUE THREAD

**Issue by zhangjianseu** [byte-fe/react-model#83]
TypeError: Cannot read property 'state' of undefined
j
node_modules/react-model/dist/react-model.js:253
  250 |   }), e;
  251 | },
  252 |     j = function j(t, e) {
> 253 |   var r = n.useState(o.State[t].state)[1];
  254 |   o.uid += 1;
  255 |   var c = "" + o.uid;
  256 |   o.Setter.functionSetter[t] || (o.Setter.functionSetter[t] = {}), o.Setter.functionSetter[t][c] = {
View compiled
WorkSpaceList
src/views/Pages/WorkSpace/List/index.tsx:16
  13 |     star: boolean,
  14 |     members: string[]
  15 | }
> 16 | const WorkSpaceList = () => {
  17 |     const [newDialogVisible, setNewDialogVisible] = useState(false);
  18 |     const [state, actions] = useStore('WorkSpaceList');
  19 |

**Comment by ArrayZoneYour** [comment]
可以提供下复现问题的Codesandbox或者仓库地址吗？

可能是你的Model方法执行滞后了，可以Model初始化代码加在入口页试下
```
Model({ WorkSpaceList }) 
```
